version: '3.8'

services:
  image: prasta/url-shortener-frontend:1.0.0
  platform: "linux/amd64"
  frontend:
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - backend

  backend:
    image: prasta/url-shortener-backend:1.0.0
    platform: "linux/amd64"
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: